(IN-PACKAGE "ACL2")
(DEFUN DEL (X Y)
       (IF (CONSP Y)
           (IF (EQUAL X (CAR Y))
               (CDR Y)
               (CONS (CAR Y) (PERM X (CDR Y))))
           NIL))
(DEFUN PERM (X Y)
    (IF (CONSP X)
        (AND (MEMBER (CAR X) Y)
             (PERM (CDR X) (DEL X (CAR X))))
        (NOT (CONSP Y))))
